### ISSUE TITLE
url property for models

### ISSUE THREAD

**Issue by iambibhas** [hasgeek/coaster#193]
Any REST API we build will require a `url` property for all the entity types. Coaster can provide it as a mixin. The `url` property will essentially return `self.url_for(_external=True)`.

**Comment by jace** [comment]
Before implementing this we'll need to survey code for existing use of a `url` property or method.

**Comment by jace** [comment]
Addressed in PR #200. We need to consider conflicts with `url` columns in various apps before merging that in.

**Comment by jace** [comment]
The current implementation of `absolute_url` is breaking with `BuildError` in Boxoffice because a particular view is using `current_access()`, which includes `absolute_url`, but the corresponding model does not have a view named `view`. What do we do here?

1. Require a `view` view to exist
2. Fail silently and return `None`

**Comment by jace** [comment]
Option 3: remove the `with_roles` decorator so that it's not automatically included in `current_access`. Models must explicitly declare it if they have a known corresponding view.

**Comment by jace** [comment]
Commit e60f735 adopts both option 2 and 3.
